import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';

import '../data/built_in_stories.dart';
import '../models/story_generation_models.dart';
import '../models/story_models.dart';
import '../prompts/character_extraction_prompt.dart';
import '../prompts/cover_art_prompt.dart';
import '../prompts/panel_art_prompt.dart';
import '../prompts/panel_description_prompt.dart';
import '../secrets/openrouter_secret.dart' as local_secret;
import '../utils/app_logger.dart';
import '../utils/reading_level_helper.dart';
import '../utils/story_text_utils.dart';
import '../models/story_world_models.dart';
import '../config/model_config.dart';
import 'openrouter_image_client.dart';
import 'openrouter_story_client.dart';
import 'story_panel_art_service.dart';
import 'story_storage_service.dart';
import 'story_world_service.dart';

class StoryGeneratorService {
  StoryGeneratorService({
    OpenRouterStoryClient? client,
    StoryStorageService? storage,
    OpenRouterImageClient? imageClient,
  }) : _client = client ?? OpenRouterStoryClient(),
       _storage = storage ?? StoryStorageService.instance,
       _imageClient = imageClient ?? OpenRouterImageClient();

  final OpenRouterStoryClient _client;
  final StoryStorageService _storage;
  final OpenRouterImageClient _imageClient;
  final StoryWorldService _storyWorldService = StoryWorldService.instance;

  Future<GeneratedStoryRecord> generateStory(
    StoryGenerationRequest request,
  ) async {
    final start = DateTime.now();
    AppLogger.system.d(
      'StoryGeneratorService: request(level=${request.readingLevel}, minutes=${request.durationMinutes}, model=${request.model})',
    );
    final result = await _client.generateStoryPayload(request);
    final elapsedMs = DateTime.now().difference(start).inMilliseconds;
    if (AppLogger.enableGenAiLogging) {
      AppLogger.genai.success(
        'Story pipeline: story payload generated by model=${result.modelId} in ${elapsedMs}ms',
      );
    }
    final record = _recordFromPayload(result.payload, request, result.modelId);
    await _storage.saveStory(record);
    AppLogger.system.emoji(
      '📖',
      'Stored story "${record.chapter.title}" (${record.id})',
    );
    return record;
  }

  Future<List<GeneratedStoryRecord>> loadStories() async {
    final stored = await _storage.loadStories();
    final builtIns = BuiltInStoryLibrary.loadStories();
    return [...stored, ...builtIns];
  }

  Future<void> deleteStory(String storyId) => _storage.deleteStory(storyId);

  Future<GeneratedStoryRecord?> recordStoryOpened(String storyId) async {
    return _storage.updateStory(storyId, (current) {
      final now = DateTime.now();
      final updatedMoments = List<DateTime>.from(current.readMoments)..add(now);
      if (updatedMoments.length > 30) {
        updatedMoments.removeRange(0, updatedMoments.length - 30);
      }
      return current.copyWith(
        readCount: current.readCount + 1,
        lastReadAt: now,
        readMoments: updatedMoments,
      );
    });
  }

  Future<GeneratedStoryRecord?> toggleFavorite(
    String storyId, {
    bool? value,
  }) async {
    return _storage.updateStory(storyId, (current) {
      final desired = value ?? !current.isFavorite;
      return current.copyWith(isFavorite: desired);
    });
  }

  Future<GeneratedStoryRecord?> setChildRating(
    String storyId,
    int? rating,
  ) async {
    return _storage.updateStory(
      storyId,
      (current) => current.copyWith(
        childRating: rating,
        isFavorite: rating != null && rating >= 4,
      ),
    );
  }

  Future<GeneratedStoryRecord?> updateStoryTitle(
    String storyId,
    String newTitle,
  ) {
    final trimmed = newTitle.trim();
    if (trimmed.isEmpty) {
      throw ArgumentError('Title cannot be empty.');
    }
    return _storage.updateStory(storyId, (current) {
      final updatedChapter = StoryChapter(
        id: current.chapter.id,
        title: trimmed,
        beats: current.chapter.beats,
        choicePoints: current.chapter.choicePoints,
        metadata: current.chapter.metadata,
      );
      return current.copyWith(chapter: updatedChapter);
    });
  }

  Future<GeneratedStoryRecord?> updateStoryCover(
    String storyId,
    String? coverPath, {
    String? modelId,
  }) {
    return _storage.updateStory(storyId, (current) {
      return current.copyWith(
        coverImagePath: coverPath,
        coverModelId: coverPath == null ? null : modelId ?? current.coverModelId,
      );
    });
  }

  Future<GeneratedStoryRecord?> updateStoryPanelArt(
    String storyId,
    StoryPanelArtMetadata? art,
  ) {
    return _storage.updateStory(storyId, (current) {
      return current.copyWith(panelArt: art);
    });
  }

  Future<GeneratedStoryRecord?> updateStoryText(
    String storyId,
    String rawText,
  ) {
    final sanitized = rawText.trim();
    if (sanitized.isEmpty) {
      throw ArgumentError('Story text cannot be empty.');
    }
    return _storage.updateStory(storyId, (current) {
      final updatedBeats = _beatsFromRawText(sanitized);
      final updatedChapter = StoryChapter(
        id: current.chapter.id,
        title: current.chapter.title,
        beats: updatedBeats,
        choicePoints: current.chapter.choicePoints,
        metadata: current.chapter.metadata,
      );
      final band = ReadingLevelHelper.bandForLevel(current.readingLevel);
      final familiarity = _computeFamiliarity(updatedChapter, band);
      return current.copyWith(
        chapter: updatedChapter,
        totalWordCount: familiarity.totalWords,
        familiarWordCount: familiarity.familiarCount,
        familiarWordRatio: familiarity.ratio,
      );
    });
  }

  Future<StoryRevisionDraft> draftRevision(
    GeneratedStoryRecord story,
    String instructions,
  ) async {
    final trimmed = instructions.trim();
    if (trimmed.isEmpty) {
      throw ArgumentError('Please describe what you want to revise.');
    }
    final result = await _client.reviseStoryPayload(
      story: story,
      instructions: trimmed,
    );
    final draft = _recordFromRevisionPayload(
      base: story,
      payload: result.payload,
      modelUsed: result.modelId,
    );
    return StoryRevisionDraft(
      record: draft,
      modelId: result.modelId,
      instructions: trimmed,
    );
  }

  Future<GeneratedStoryRecord?> applyRevision({
    required String storyId,
    required StoryRevisionDraft draft,
  }) {
    return _storage.updateStory(storyId, (current) {
      final nextVersion = current.version + 1;
      final revisionEntry = StoryRevision(
        version: nextVersion,
        instructions: draft.instructions,
        storyText: StoryTextUtils.narrationOnly(draft.record.chapter),
        createdAt: DateTime.now(),
        modelId: draft.modelId,
      );
      final history = List<StoryRevision>.from(current.revisions)
        ..add(revisionEntry);
      final updatedChapter = StoryChapter(
        id: current.chapter.id,
        title: draft.record.chapter.title,
        beats: draft.record.chapter.beats,
        choicePoints: draft.record.chapter.choicePoints,
        metadata: draft.record.chapter.metadata,
      );
      return current.copyWith(
        chapter: updatedChapter,
        summary: draft.record.summary,
        readingLevel: draft.record.readingLevel,
        durationMinutes: draft.record.durationMinutes,
        focusWords: draft.record.focusWords,
        familiarWordRatio: draft.record.familiarWordRatio,
        familiarWordCount: draft.record.familiarWordCount,
        totalWordCount: draft.record.totalWordCount,
        model: draft.modelId,
        version: nextVersion,
        revisions: history,
      );
    });
  }

  /// Extract character descriptions for a given story, suitable for
  /// Story World suggestions or downstream art prompts.
  Future<String> extractCharacterDescriptionsForStory(
    GeneratedStoryRecord story,
  ) async {
    final storyText = StoryTextUtils.narrationOnly(story.chapter);
    final context = await _buildPersistentCharacterContext(story);
    return _extractCharacters(storyText, extraContext: context);
  }

  GeneratedStoryRecord _recordFromPayload(
    Map<String, dynamic> payload,
    StoryGenerationRequest request,
    String modelUsed,
  ) {
    final beats = _parseBeats(payload['beats']);
    final choicePoints = _parseChoicePoints(payload['choice_points']);
    final storyId = payload['id']?.toString().trim().isNotEmpty == true
        ? payload['id'].toString()
        : 'story_${DateTime.now().millisecondsSinceEpoch}';
    final title = payload['title'] as String? ?? 'Story Time Adventure';
    final summary = payload['summary'] as String? ?? '';
    final metadata = Map<String, dynamic>.from(
      payload['metadata'] as Map<String, dynamic>? ?? {},
    );
    metadata['generated_via'] = 'openrouter';
    metadata['requested_at'] = request.requestedAt.toIso8601String();
    metadata['parent_prompt'] = request.parentPrompt;
    metadata['child_context'] = request.childContext;
    metadata['model_used'] = modelUsed;
    metadata['reading_band'] = request.readingBand.toJson();
    metadata['include_child_name'] = request.includeChildName;
    metadata['child_name'] = request.includeChildName
        ? request.childName
        : null;

    final chapter = StoryChapter(
      id: storyId,
      title: title,
      beats: beats,
      choicePoints: choicePoints,
      metadata: metadata,
    );

    final focusWords = (payload['focus_words'] as List<dynamic>? ?? [])
        .map((e) => e.toString())
        .toList();
    final estimatedMinutes =
        (payload['estimated_minutes'] as num?)?.toInt() ??
        request.durationMinutes;
    final readingLevel =
        payload['reading_level'] as int? ?? request.readingLevel;
    final familiarityStats = _computeFamiliarity(chapter, request.readingBand);

    return GeneratedStoryRecord(
      id: storyId,
      chapter: chapter,
      summary: summary,
      readingLevel: readingLevel,
      durationMinutes: estimatedMinutes,
      focusWords: focusWords,
      familiarWordRatio: familiarityStats.ratio,
      familiarWordCount: familiarityStats.familiarCount,
      totalWordCount: familiarityStats.totalWords,
      parentPrompt: request.parentPrompt,
      childContext: request.childContext,
      storyConcept: request.storyConcept,
      model: modelUsed,
      includeChildName: request.includeChildName,
      createdAt: DateTime.now(),
      requestInputs: request.toMap(),
      isFavorite: false,
      readCount: 0,
      lastReadAt: null,
      childRating: null,
      isBuiltIn: false,
    );
  }

  GeneratedStoryRecord _recordFromRevisionPayload({
    required GeneratedStoryRecord base,
    required Map<String, dynamic> payload,
    required String modelUsed,
  }) {
    final beats = _parseBeats(payload['beats']);
    final choicePoints = _parseChoicePoints(payload['choice_points']);
    final title = payload['title'] as String? ?? base.chapter.title;
    final summary = payload['summary'] as String? ?? base.summary;
    final focusWords =
        (payload['focus_words'] as List<dynamic>? ?? base.focusWords)
            .map((e) => e.toString())
            .toList();
    final estimatedMinutes =
        (payload['estimated_minutes'] as num?)?.toInt() ?? base.durationMinutes;
    final readingLevel = payload['reading_level'] as int? ?? base.readingLevel;

    final metadata = Map<String, dynamic>.from(base.chapter.metadata ?? {});
    metadata['last_revision_model'] = modelUsed;
    metadata['last_revision_at'] = DateTime.now().toIso8601String();

    final chapter = StoryChapter(
      id: base.chapter.id,
      title: title,
      beats: beats,
      choicePoints: choicePoints,
      metadata: metadata,
    );

    final band = ReadingLevelHelper.bandForLevel(readingLevel);
    final familiarityStats = _computeFamiliarity(chapter, band);

    return base.copyWith(
      chapter: chapter,
      summary: summary,
      readingLevel: readingLevel,
      durationMinutes: estimatedMinutes,
      focusWords: focusWords,
      familiarWordRatio: familiarityStats.ratio,
      familiarWordCount: familiarityStats.familiarCount,
      totalWordCount: familiarityStats.totalWords,
      model: modelUsed,
    );
  }

  List<StoryBeat> _parseBeats(dynamic beatsJson) {
    final beatsList = (beatsJson as List<dynamic>? ?? [])
        .cast<Map<String, dynamic>?>();
    return beatsList.asMap().entries.map((entry) {
      final beat = entry.value ?? {};
      return StoryBeat(
        id: beat['id']?.toString().isNotEmpty == true
            ? beat['id'].toString()
            : 'beat_${entry.key + 1}',
        type: _parseBeatType(beat['type']),
        text: beat['text']?.toString() ?? '',
        speaker: _parseSpeaker(beat['speaker']),
        targetWords: (beat['target_words'] as List<dynamic>? ?? [])
            .map((e) => e.toString())
            .toList(),
        coachPhrase: beat['coach_phrase']?.toString(),
      );
    }).toList();
  }

  List<ChoicePoint> _parseChoicePoints(dynamic choiceJson) {
    final list = (choiceJson as List<dynamic>? ?? [])
        .cast<Map<String, dynamic>?>();
    return list.map((choice) {
      final choices = (choice?['choices'] as List<dynamic>? ?? [])
          .map((c) => c as Map<String, dynamic>? ?? {})
          .toList();
      return ChoicePoint(
        id:
            choice?['id']?.toString() ??
            'choice_${DateTime.now().millisecondsSinceEpoch}',
        beatIndex: (choice?['beat_index'] as num?)?.toInt() ?? 0,
        promptText: choice?['prompt_text']?.toString() ?? '',
        choices: choices
            .map(
              (c) => StoryChoice(
                id:
                    c['id']?.toString() ??
                    'choice_option_${Random().nextInt(9999)}',
                previewText: c['preview_text']?.toString() ?? '',
                choiceText: c['choice_text']?.toString() ?? '',
              ),
            )
            .toList(),
      );
    }).toList();
  }

  List<StoryBeat> _beatsFromRawText(String text) {
    final normalized = text.replaceAll('\r\n', '\n').trim();
    final segments = normalized
        .split(RegExp(r'\n{2,}'))
        .map((segment) => segment.trim())
        .where((segment) => segment.isNotEmpty)
        .toList();
    if (segments.isEmpty) {
      segments.add(normalized);
    }
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    return segments.asMap().entries.map((entry) {
      return StoryBeat(
        id: 'edited_${timestamp}_${entry.key + 1}',
        type: BeatType.narration,
        text: entry.value,
        speaker: Speaker.parent,
      );
    }).toList();
  }

  _FamiliarityStats _computeFamiliarity(
    StoryChapter chapter,
    ReadingBand readingBand,
  ) {
    final vocab = ReadingLevelHelper.vocabularyForBand(
      readingBand,
    ).map((w) => w.toLowerCase()).toSet();
    final words = chapter.beats
        .expand(
          (beat) => beat.text
              .replaceAll(RegExp(r"[^\w\s']"), '')
              .toLowerCase()
              .split(RegExp(r'\s+')),
        )
        .where((w) => w.isNotEmpty)
        .toList();
    if (words.isEmpty) {
      return _FamiliarityStats.zero();
    }
    final familiarCount = words.where(vocab.contains).length;
    final ratio = familiarCount / words.length;
    return _FamiliarityStats(
      familiarCount: familiarCount,
      totalWords: words.length,
      ratio: ratio,
    );
  }

  BeatType _parseBeatType(dynamic type) {
    switch (type?.toString().toLowerCase()) {
      case 'child_turn':
      case 'child':
        return BeatType.childTurn;
      case 'coach':
      case 'coach_intervention':
      case 'coaching':
        return BeatType.coachIntervention;
      case 'celebration':
        return BeatType.celebration;
      case 'narration':
      default:
        return BeatType.narration;
    }
  }

  Speaker? _parseSpeaker(dynamic speaker) {
    switch (speaker?.toString().toLowerCase()) {
      case 'parent':
        return Speaker.parent;
      case 'coach':
        return Speaker.coach;
      case 'child':
        return Speaker.child;
      default:
        return null;
    }
  }

  /// Generate panel art for a story.
  /// 
  /// This method performs the full panel art generation flow:
  /// 1. Gather canonical Story World character context
  /// 2. Generate panel descriptions (leaning on that context)
  /// 3. Generate one or more panel art grids (up to 16 panels per grid)
  /// 4. Slice and save panels
  /// 
  /// [story] - The story record to generate art for
  /// [childAge] - Optional child age for style description
  /// [onProgress] - Optional callback for progress updates
  Future<StoryPanelArtMetadata> generatePanelArt(
    GeneratedStoryRecord story, {
    int? childAge,
    String? panelModelId,
    void Function(String step)? onProgress,
  }) async {
    final overallStart = DateTime.now();
    onProgress?.call('Gathering character context...');
    
    // Step 1: Gather Story World character context (canonical descriptions).
    final storyText = StoryTextUtils.narrationOnly(story.chapter);
    final persistentContext = await _buildPersistentCharacterContext(story);

    // Persist inputs for debugging/inspection.
    await _writeDebugArtifact(
      story.id,
      'panel_descriptions_input.txt',
      [
        'STORY ID: ${story.id}',
        'MODEL (panel descriptions): ${ModelConfig.defaultPanelDescriptionModelId}',
        '',
        '=== STORY WORLD CHARACTER CONTEXT ===',
        (persistentContext ?? '(none)').trim(),
        '',
        '=== STORY TEXT (NARRATION ONLY) ===',
        storyText,
      ].join('\n'),
    );
    
    onProgress?.call('Writing panel descriptions...');
    
    // Step 2: Generate panel descriptions using Story World context instead of
    // an additional extraction pass. This reduces latency and relies on the
    // canonical Story Friend descriptions as "global" character info.
    final descStart = DateTime.now();
    final panelDescriptions = await _generatePanelDescriptions(
      storyText: storyText,
      characterContext: persistentContext,
      modelId: ModelConfig.defaultPanelDescriptionModelId,
    );
    if (AppLogger.enableGenAiLogging) {
      final ms = DateTime.now().difference(descStart).inMilliseconds;
      AppLogger.genai.success(
        'Panel pipeline: generated ${panelDescriptions.length} panel descriptions in ${ms}ms',
    );
    }
    await _writeDebugArtifact(
      story.id,
      'panel_descriptions_output.txt',
      panelDescriptions.join('\n\n----\n\n'),
    );
    
    onProgress?.call('Painting panels...');
    
    // Step 3: Generate one or more panel art grids
    final panelCount = panelDescriptions.length;
    final styleDescription = _buildStyleDescription(childAge);
    final batchDir = await _createBatchDirectory(story.id);
    final tempDir = await _getTempDirectory();
    final panelArtService = StoryPanelArtService();

    final allPanelPaths = <String>[];
    final sheetPaths = <String>[];

    // We support arbitrarily many panels by generating multiple 4×4 grids.
    // Each grid paints up to 16 panels; remaining cells are left blank
    // (as instructed in the image system prompt).
    const maxPerGrid = 16;
    final totalPanels = panelDescriptions.length;
    final gridCount = (totalPanels / maxPerGrid).ceil().clamp(1, 1000);

    for (int pageIndex = 0; pageIndex < gridCount; pageIndex++) {
      final startIndex = pageIndex * maxPerGrid;
      if (startIndex >= totalPanels) break;
      final endIndex = min(startIndex + maxPerGrid, totalPanels);
      final pageDescriptions = panelDescriptions.sublist(startIndex, endIndex);
      final pagePanelCount = pageDescriptions.length;

      onProgress?.call('Painting panels (page ${pageIndex + 1} of $gridCount)...');

      final panelArtPrompt = _buildPanelArtPrompt(
        panelCount: pagePanelCount,
        panelDescriptions: pageDescriptions,
        styleDescription: styleDescription,
      );

      await _writeDebugArtifact(
        story.id,
        'panel_art_prompt_page_${pageIndex + 1}.txt',
        panelArtPrompt,
      );

      final paintStart = DateTime.now();
      final imageResult = pageIndex == 0
          ? await _imageClient.generateImage(
              prompt: panelArtPrompt,
              modelId: panelModelId ?? OpenRouterImageClient.panelModel,
              aspectRatio: '1:1',
              systemPrompt: panelArtPrompt,
            )
          : await _imageClient.generateImageWithInput(
              prompt: panelArtPrompt,
              imagePath: sheetPaths.first,
              modelId: panelModelId ?? OpenRouterImageClient.panelModel,
              aspectRatio: '1:1',
              systemPrompt: panelArtPrompt,
            );
      if (AppLogger.enableGenAiLogging) {
        final ms = DateTime.now().difference(paintStart).inMilliseconds;
        AppLogger.genai.success(
          'Panel pipeline: image grid page ${pageIndex + 1}/$gridCount generated by model=${imageResult.modelId} in ${ms}ms',
        );
      }

      onProgress?.call('Slicing artwork (page ${pageIndex + 1} of $gridCount)...');

      // Save and slice this grid
      final sliceStart = DateTime.now();
      final gridPath = await _imageClient.saveImageFromDataUrl(
        dataUrl: imageResult.imageDataUrl,
        fileName:
            'panel_grid_${story.id}_${DateTime.now().millisecondsSinceEpoch}_p${pageIndex + 1}.png',
        directory: tempDir.path,
      );
      sheetPaths.add(gridPath);

      final pagePanelPaths = await panelArtService.processPanelGrid(
        gridImagePath: gridPath,
        outputDir: batchDir.path,
        panelCount: pagePanelCount,
      );
      allPanelPaths.addAll(pagePanelPaths);

      if (AppLogger.enableGenAiLogging) {
        final sliceMs = DateTime.now().difference(sliceStart).inMilliseconds;
        AppLogger.genai.success(
          'Panel pipeline: sliced ${pagePanelPaths.length} panels from page ${pageIndex + 1}/$gridCount in ${sliceMs}ms',
        );
      }
    }

    // Create metadata for the entire panel set. We standardize on 4×4 grids.
    final metadata = StoryPanelArtMetadata(
      columns: 4,
      rows: 4,
      panelImagePaths: allPanelPaths,
      sheetImagePath: sheetPaths.isNotEmpty ? sheetPaths.first : '',
      sheetImagePaths: sheetPaths,
      importedAt: DateTime.now(),
      assignments: _createDefaultAssignments(panelCount, allPanelPaths),
      modelId: panelModelId ?? OpenRouterImageClient.panelModel,
    );
    
    // Save to story
    await updateStoryPanelArt(story.id, metadata);

    final totalMs = DateTime.now().difference(overallStart).inMilliseconds;
    if (AppLogger.enableGenAiLogging) {
      AppLogger.genai.success(
        'Panel pipeline: generated ${allPanelPaths.length} panels across $gridCount grids; '
        'total pipeline=${totalMs}ms',
      );
    }

    onProgress?.call('Done!');

    return metadata;
  }

  /// Generate cover art for a story.
  /// 
  /// [story] - The story record to generate cover for
  /// [panelArtImagePath] - Optional path to panel art grid (for visual reference)
  /// [childAge] - Optional child age for style description
  /// [onProgress] - Optional callback for progress updates
  Future<String> generateCoverArt(
    GeneratedStoryRecord story, {
    String? panelArtImagePath,
    int? childAge,
    String? coverModelId,
    void Function(String step)? onProgress,
  }) async {
    final overallStart = DateTime.now();
    onProgress?.call('Creating cover art...');
    
    final storyText = StoryTextUtils.narrationOnly(story.chapter);
    final characterContext =
        (await _buildPersistentCharacterContext(story)) ?? '';

    // Validate that the reference panel art image still exists.
    // If the file is missing (e.g., temp directory cleared), fall back
    // gracefully to text-only cover generation.
    String? effectivePanelArtPath = panelArtImagePath;
    bool hasPanelArtForPrompt = panelArtImagePath != null;
    if (effectivePanelArtPath != null) {
      final file = File(effectivePanelArtPath);
      if (!await file.exists()) {
        AppLogger.system.w(
          'Cover art: panel art sheet missing at $effectivePanelArtPath. '
          'Falling back to text-only cover generation.',
        );
        effectivePanelArtPath = null;
        hasPanelArtForPrompt = false;
      }
    }

    final coverPrompt = _buildCoverArtPrompt(
      story: story,
      storyText: storyText,
      childAge: childAge,
      hasPanelArt: hasPanelArtForPrompt,
      characterContext: characterContext,
    );
    
    String? coverPath;
    String? modelUsed = coverModelId;
    
    if (effectivePanelArtPath != null) {
      try {
      // Generate with panel art as reference
      final refStart = DateTime.now();
      final imageResult = await _imageClient.generateImageWithInput(
        prompt: coverPrompt,
          imagePath: effectivePanelArtPath,
          modelId: coverModelId ?? OpenRouterImageClient.coverModel,
        aspectRatio: '3:4',
        systemPrompt: coverArtPromptWithPanelArt,
      );
        modelUsed = imageResult.modelId;
      if (AppLogger.enableGenAiLogging) {
        final ms = DateTime.now().difference(refStart).inMilliseconds;
        AppLogger.genai.success(
          'Cover pipeline: reference-image generation via model=${imageResult.modelId} '
          'completed in ${ms}ms',
        );
      }
      
      final coversDir = await _getCoversDirectory();
      coverPath = await _imageClient.saveImageFromDataUrl(
        dataUrl: imageResult.imageDataUrl,
          fileName:
              'cover_${story.id}_${DateTime.now().millisecondsSinceEpoch}.jpg',
        directory: coversDir.path,
      );
      } on FileSystemException catch (e, stack) {
        // Log and fall back to text-only cover instead of surfacing a raw
        // filesystem error to the user.
        AppLogger.system.e(
          'Cover art: reference image missing at $effectivePanelArtPath. '
          'Falling back to text-only cover generation.',
          error: e,
          stackTrace: stack,
        );
        effectivePanelArtPath = null;
      }
    }

    if (effectivePanelArtPath == null) {
      // Generate without panel art
      final textOnlyStart = DateTime.now();
      final imageResult = await _imageClient.generateImage(
        prompt: coverPrompt,
        modelId: coverModelId ?? OpenRouterImageClient.coverModel,
        aspectRatio: '3:4',
        systemPrompt: coverArtPromptWithoutPanelArt,
      );
      modelUsed = imageResult.modelId;
      if (AppLogger.enableGenAiLogging) {
        final ms = DateTime.now().difference(textOnlyStart).inMilliseconds;
        AppLogger.genai.success(
          'Cover pipeline: text-only cover via model=${imageResult.modelId} '
          'completed in ${ms}ms',
        );
      }
      
      final coversDir = await _getCoversDirectory();
      coverPath = await _imageClient.saveImageFromDataUrl(
        dataUrl: imageResult.imageDataUrl,
        fileName: 'cover_${story.id}_${DateTime.now().millisecondsSinceEpoch}.jpg',
        directory: coversDir.path,
      );
    }
    
    // Save to story, including model used
    await updateStoryCover(
      story.id,
      coverPath,
      modelId: modelUsed,
    );
    
    final totalMs = DateTime.now().difference(overallStart).inMilliseconds;
    if (AppLogger.enableGenAiLogging) {
      AppLogger.genai.success('Cover pipeline: total=${totalMs}ms');
    }
    
    onProgress?.call('Done!');
    
    return coverPath!;
  }

  Future<String> _extractCharacters(
    String storyText, {
    String? extraContext,
  }) async {
    final buffer = StringBuffer();
    if (extraContext != null && extraContext.trim().isNotEmpty) {
      buffer.writeln('ADDITIONAL CHARACTER CONTEXT FROM STORY WORLD:');
      buffer.writeln(extraContext.trim());
      buffer.writeln();
      buffer.writeln('STORY TEXT:');
    }
    buffer.writeln(storyText);

    final result = await _callTextModel(
      systemPrompt: characterExtractionPrompt,
      userPrompt: buffer.toString(),
      modelId: ModelConfig.defaultCharacterExtractionModelId,
      temperature: 0.3,
      maxOutputTokens: 1024,
    );
    
    return result;
  }

  Future<List<String>> _generatePanelDescriptions({
    required String storyText,
    String? characterContext,
    String? modelId,
  }) async {
    final buffer = StringBuffer();
    if (characterContext != null && characterContext.trim().isNotEmpty) {
      buffer.writeln(
        'CANONICAL STORY FRIEND DESCRIPTIONS FROM STORY WORLD (GLOBAL CONTEXT):',
      );
      buffer.writeln(characterContext.trim());
      buffer.writeln();
      buffer.writeln(
        'IMPORTANT: Do NOT repeat these long descriptions in every panel. '
        'Assume them as given canon. Only describe character details that '
        'change within this scene (pose, expression, local action, props).',
      );
      buffer.writeln();
    }

    buffer.writeln('FULL STORY TEXT (NARRATION ONLY):');
    buffer.writeln(storyText);
    
    final result = await _callTextModel(
      systemPrompt: panelDescriptionPrompt,
      userPrompt: buffer.toString(),
      modelId: modelId,
      temperature: 0.7,
      maxOutputTokens: 4096,
    );
    
    // Parse panel descriptions (assume they're numbered: Panel 1, Panel 2, etc.)
    final panels = <String>[];
    final lines = result.split('\n');
    String? currentPanel;
    
    for (final line in lines) {
      if (line.trim().toLowerCase().startsWith(RegExp(r'panel \d+'))) {
        if (currentPanel != null && currentPanel.trim().isNotEmpty) {
          panels.add(currentPanel.trim());
        }
        currentPanel = line.trim();
      } else if (currentPanel != null) {
        currentPanel += '\n$line';
      }
    }
    
    if (currentPanel != null && currentPanel.trim().isNotEmpty) {
      panels.add(currentPanel.trim());
    }
    
    // Fallback: if no panels found, split by double newlines
    if (panels.isEmpty) {
      final paragraphs = result.split(RegExp(r'\n{2,}'));
      panels.addAll(paragraphs.where((p) => p.trim().isNotEmpty));
    }
    
    // Ensure we have at least one panel
    if (panels.isEmpty) {
      panels.add(result.trim());
    }
    
    return panels;
  }

  /// Call OpenRouter for text generation (not JSON).
  Future<String> _callTextModel({
    required String systemPrompt,
    required String userPrompt,
    String? modelId,
    double temperature = 0.7,
    int maxOutputTokens = 2048,
  }) async {
    final apiKey = _getApiKey();
    if (apiKey.isEmpty) {
      throw StateError('OPENROUTER_API_KEY missing');
    }

    final model = modelId ?? ModelConfig.defaultStoryModelId;
    final body = {
      'model': model,
      'temperature': temperature,
      'top_p': 0.9,
      'max_output_tokens': maxOutputTokens,
      'messages': [
        {'role': 'system', 'content': systemPrompt},
        {'role': 'user', 'content': userPrompt},
      ],
    };

    final start = DateTime.now();
    if (AppLogger.enableGenAiLogging) {
      final chars = userPrompt.length + systemPrompt.length;
      final approxTokens = (chars / 4).round();
      AppLogger.genai.progress(
        'Text request → model=$model temp=$temperature '
        'maxTokens=$maxOutputTokens chars=$chars approxTokens=$approxTokens',
      );
      if (AppLogger.enableGenAiVerbose) {
        AppLogger.genai.i('TEXT SYSTEM PROMPT (model=$model):\n$systemPrompt');
        AppLogger.genai.i('TEXT USER PROMPT (model=$model):\n$userPrompt');
      }
    } else {
      AppLogger.system.d('Calling OpenRouter for text generation (model=$model)');
    }

    final httpClient = http.Client();
    final response = await httpClient.post(
      Uri.parse('https://openrouter.ai/api/v1/chat/completions'),
      headers: {
        'Authorization': 'Bearer $apiKey',
        'Content-Type': 'application/json',
        'HTTP-Referer': 'https://xen.words.app/dev',
        'X-Title': 'Xen Words',
      },
      body: jsonEncode(body),
    );

    if (response.statusCode >= 400) {
      AppLogger.system.e('OpenRouter error: ${response.statusCode} ${response.body}');
      throw Exception('OpenRouter API error ${response.statusCode}: ${response.body}');
    }

    final decoded = jsonDecode(response.body) as Map<String, dynamic>;
    final choices = decoded['choices'] as List<dynamic>? ?? [];
    if (choices.isEmpty) {
      throw StateError('OpenRouter returned no choices');
    }

    final content = choices.first['message']['content'];
    final contentString = content is List
        ? content.map((e) => e['text'] ?? '').join('\n')
        : content?.toString() ?? '';

    httpClient.close();
    if (AppLogger.enableGenAiLogging) {
      final elapsedMs = DateTime.now().difference(start).inMilliseconds;
      AppLogger.genai.success(
        'Text response ← model=$model elapsed=${elapsedMs}ms '
        'outChars=${contentString.length}',
      );
      if (AppLogger.enableGenAiVerbose) {
        AppLogger.genai.i('TEXT RAW OUTPUT (model=$model):\n$contentString');
      }
    }
    return contentString;
  }

  String _getApiKey() {
    final localKey = local_secret.openRouterApiKey.trim();
    if (localKey.isNotEmpty) {
      return localKey;
    }
    return const String.fromEnvironment('OPENROUTER_API_KEY');
  }

  String _buildStyleDescription(int? childAge) {
    final ageText = childAge != null ? 'age-appropriate for $childAge years old' : 'age-appropriate';
    return 'Whimsical children\'s book illustration style, vibrant colors, soft lighting, $ageText, warm and engaging';
  }

  /// Write a debug artifact (prompt, model output, etc.) to the same cache
  /// directory used for panel grids, so external tools can pull and inspect it.
  Future<void> _writeDebugArtifact(
    String storyId,
    String fileName,
    String contents,
  ) async {
    try {
      final dir = await _getTempDirectory();
      final sanitizedId =
          storyId.replaceAll(RegExp(r'[^a-zA-Z0-9_\-]'), '_');
      final path = '${dir.path}/${sanitizedId}_$fileName';
      final file = File(path);
      await file.writeAsString(contents);
    } catch (e, stack) {
      AppLogger.system.w(
        'Failed to write debug artifact $fileName for story $storyId',
        error: e,
        stackTrace: stack,
      );
    }
  }

  String _buildPanelArtPrompt({
    required int panelCount,
    required List<String> panelDescriptions,
    required String styleDescription,
  }) {
    final panelList = panelDescriptions
        .asMap()
        .entries
        .map((e) => 'Panel ${e.key + 1}:\n${e.value}')
        .join('\n\n');
    
    return panelArtPrompt
        .replaceAll('[N]', panelCount.toString())
        .replaceAll('[ART_STYLE_DESCRIPTION]', styleDescription)
        .replaceAll('[PANEL_LIST]', panelList);
  }

  String _buildCoverArtPrompt({
    required GeneratedStoryRecord story,
    required String storyText,
    int? childAge,
    required bool hasPanelArt,
    required String characterContext,
  }) {
    final ageText = childAge != null ? childAge.toString() : '5-8';
    
    if (hasPanelArt) {
      return coverArtPromptWithPanelArt
          .replaceAll('[STORY_TITLE]', story.chapter.title)
          .replaceAll('[STORY_SUMMARY]', story.summary)
          .replaceAll('[CHILD_AGE]', ageText);
    } else {
      return coverArtPromptWithoutPanelArt
          .replaceAll('[STORY_TITLE]', story.chapter.title)
          .replaceAll('[STORY_SUMMARY]', story.summary)
          .replaceAll('[FULL_STORY_TEXT]', storyText)
          .replaceAll('[CHILD_AGE]', ageText)
          .replaceAll('[CHARACTER_DESCRIPTIONS]', characterContext);
    }
  }


  Map<int, String> _createDefaultAssignments(int panelCount, List<String> panelPaths) {
    final assignments = <int, String>{};
    for (int i = 0; i < panelCount && i < panelPaths.length; i++) {
      assignments[i] = panelPaths[i];
    }
    return assignments;
  }

  Future<Directory> _getTempDirectory() async {
    final dir = Directory.systemTemp;
    final tempDir = Directory('${dir.path}/xen_words_art');
    if (!await tempDir.exists()) {
      await tempDir.create(recursive: true);
    }
    return tempDir;
  }

  Future<Directory> _getCoversDirectory() async {
    final docs = await _getApplicationDocumentsDirectory();
    final coversDir = Directory('${docs.path}/story_covers');
    if (!await coversDir.exists()) {
      await coversDir.create(recursive: true);
    }
    return coversDir;
  }

  Future<Directory> _createBatchDirectory(String storyId) async {
    final docs = await _getApplicationDocumentsDirectory();
    final base = Directory('${docs.path}/story_panels/$storyId');
    if (!await base.exists()) {
      await base.create(recursive: true);
    }
    final batchDir = Directory(
      '${base.path}/${DateTime.now().millisecondsSinceEpoch}',
    );
    if (!await batchDir.exists()) {
      await batchDir.create(recursive: true);
    }
    return batchDir;
  }

  Future<Directory> _getApplicationDocumentsDirectory() async {
    return await getApplicationDocumentsDirectory();
  }

  /// Build a human-readable description of Story World characters selected
  /// for this story, based on the original generation request inputs and
  /// the current Story World state.
  Future<String?> _buildPersistentCharacterContext(
    GeneratedStoryRecord story,
  ) async {
    final inputs = story.requestInputs ?? const <String, dynamic>{};
    final explicit = inputs['cast_context']?.toString();
    if (explicit != null && explicit.trim().isNotEmpty) {
      return explicit.trim();
    }

    final profileId = inputs['profile_id']?.toString();
    final rawIds = inputs['cast_character_ids'];
    if (profileId == null || rawIds is! List) {
      return null;
    }

    final ids = rawIds.map((e) => e.toString()).toList();
    if (ids.isEmpty) return null;

    try {
      final world = await _storyWorldService.loadWorld(profileId);
      final selected = ids
          .map((id) => world.characters[id])
          .whereType<StoryCharacterEntity>()
          .toList();
      if (selected.isEmpty) return null;

      final buffer = StringBuffer();
      buffer.writeln('Story Friends from the child\'s Story World:');
      for (final c in selected) {
        buffer.write('- ${c.displayName ?? 'Unnamed friend'}');
        if (c.summary != null && c.summary!.isNotEmpty) {
          buffer.write(': ${c.summary}');
        }
        if (c.traits.isNotEmpty) {
          buffer.write(' Traits: ${c.traits.join(', ')}.');
        }
        if (c.powers.isNotEmpty) {
          buffer.write(' Powers: ${c.powers.join(', ')}.');
        }
        buffer.writeln();
      }
      return buffer.toString().trim();
    } catch (e) {
      AppLogger.system.e(
        'Failed to build Story World character context for story ${story.id}',
        error: e,
      );
      return null;
    }
  }
}

class _FamiliarityStats {
  final int familiarCount;
  final int totalWords;
  final double ratio;

  const _FamiliarityStats({
    required this.familiarCount,
    required this.totalWords,
    required this.ratio,
  });

  factory _FamiliarityStats.zero() =>
      const _FamiliarityStats(familiarCount: 0, totalWords: 0, ratio: 0);
}

class StoryRevisionDraft {
  final GeneratedStoryRecord record;
  final String modelId;
  final String instructions;

  StoryRevisionDraft({
    required this.record,
    required this.modelId,
    required this.instructions,
  });
}
